# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-15 20:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_scrapper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='scrapingeventlogs',
            name='venue',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='event_scrapper.Venue'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='venue_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
