# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-19 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_scrapper', '0004_auto_20180819_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_all_day_event',
            field=models.NullBooleanField(default=False),
        ),
    ]
