# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-19 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_scrapper', '0005_auto_20180819_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
