# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-03 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event_scrapper', '0008_auto_20180903_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtlByDayCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('name', models.CharField(blank=True, max_length=10000, null=True)),
                ('slug', models.CharField(blank=True, max_length=10000, null=True)),
                ('url', models.CharField(blank=True, max_length=10000, null=True)),
                ('taxonomy', models.CharField(blank=True, max_length=10000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AtlByDayTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('tag_id', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=10000, null=True)),
                ('name', models.CharField(blank=True, max_length=10000, null=True)),
                ('slug', models.CharField(blank=True, max_length=10000, null=True)),
                ('url', models.CharField(blank=True, max_length=10000, null=True)),
                ('taxonomy', models.CharField(blank=True, max_length=10000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
